version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: psimobile_postgres
    environment:
      POSTGRES_DB: psimobile
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: psimobile_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
